---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp

steps:
  - name: install
    image: node:16
    commands:
      - yarn

  - name: build
    image: node:16
    commands:
      - yarn build
