---
kind: pipeline
type: docker
name: Preflight

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp

steps:
  - name: install
    image: node:16
    commands:
      - exit 78
      - yarn

  - name: preflight
    image: node:16
    commands:
      - yarn lint:prettier:check
      - yarn lint:eslint:check
      - yarn lint:stylelint:check
      - yarn lint:types

---
kind: pipeline
type: docker
name: Cypress (Electron / Chromium)
# why bother with Chrome and Chromium?

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp

steps:
  - name: install
    image: cypress/included:8.5.0
    commands:
      - exit 78
      - yarn

  - name: Integration tests
    image: cypress/included:8.5.0
    commands:
      - yarn test:cy

  - name: Component tests
    image: cypress/included:8.5.0
    commands:
      - yarn test:cy:ct

---
kind: pipeline
type: docker
name: Cypress (Firefox)

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp

steps:
  - name: install
    image: cypress/included:8.5.0
    commands:
      - yarn

  - name: Integration tests
    image: cypress/included:8.5.0
    commands:
      - yarn test:cy:ff

  - name: Component tests
    image: cypress/included:8.5.0
    commands:
      - yarn test:cy:ct:ff

---
kind: pipeline
type: docker
name: build

depends_on:
  - Cypress (Electron / Chromium)
  - Cypress (Firefox)
  - Preflight

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp

steps:
  - name: install
    image: node:16
    commands:
      - yarn

  - name: build
    image: node:16
    commands:
      - yarn build

---
kind: pipeline
type: docker
name: discord

depends_on:
  - build

clone:
  disable: true

trigger:
  status:
    - failure
    - success

steps:
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status:
        - success
        - failure
